name: Acceptance Tests with Zabbix

on:
  push:
    branches: [master]


jobs:
  testacc:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install Docker Compose & tools
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose make unzip curl

      - name: Launch Zabbix stack (docker-compose)
        run: |
          docker-compose -f ci/docker-compose.yaml up -d
          echo "Waiting for Zabbix frontend (port 8080)..."
          for i in {1..60}; do
            curl -sf http://localhost:8080 && break
            sleep 5
          done

      - name: check logs
        run: |
          cd ci
          docker-compose logs -f zabbix-server


      
      - name: Wait for Zabbix API to be available
        run: |
          echo "Waiting for Zabbix API (auth)..."
          for i in {1..60}; do
            RESPONSE=$(curl -s -X POST http://localhost:8080/api_jsonrpc.php \
              -H 'Content-Type: application/json' \
              -d '{
                    "jsonrpc": "2.0",
                    "method": "user.login",
                    "params": {
                      "user": "Admin",
                      "password": "zabbix"
                    },
                    "id": 1,
                    "auth": null
                  }')
            if echo "$RESPONSE" | grep -q '"result"'; then
              echo "Zabbix API ready"
              break
            fi
            echo "Still waiting..."
            sleep 5
          done

      - name: Run Go acceptance tests
        env:
          TF_ACC: 1
          ZABBIX_SERVER_URL: http://localhost:8080/api_jsonrpc.php
          ZABBIX_USER: Admin
          ZABBIX_PASSWORD: zabbix
        run: go test ./zabbix/... -v -timeout 30m

      - name: Shutdown and cleanup
        if: always()
        run: docker-compose -f ci/docker-compose.yaml down -v
